Revert "ICMSLST-414 Use eventlet with gunicorn (#165)" (#176)
This reverts commit a96c498d06d1796e321c8151c2e437b4a74efd31.

Reverts uktrade/icms#165
Error was 
redis.exceptions.ConnectionError: Error -3 connecting to redis:6379. Lookup timed out

Related problem: https://github.com/celery/celery/issues/5924